Attribute VB_Name = "ExtractMates"
' SolidWorks Macro to Extract Mate Data
' Run this from within SolidWorks: Tools > Macro > Run

Option Explicit

Sub main()
    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Dim swAssy As SldWorks.AssemblyDoc
    Dim swConfig As SldWorks.Configuration
    Dim swRootComp As SldWorks.Component2
    Dim swFeat As SldWorks.Feature
    Dim swSubFeat As SldWorks.Feature
    Dim swMate As SldWorks.Mate2
    Dim swMateEnt As SldWorks.MateEntity2
    Dim swComp As SldWorks.Component2
    Dim vComps As Variant
    Dim i As Long
    Dim j As Long
    Dim outputPath As String
    Dim fileNum As Integer
    Dim compName As String
    Dim mateName As String
    Dim mateType As String
    Dim comp1 As String
    Dim comp2 As String

    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc

    If swModel Is Nothing Then
        MsgBox "No document open!", vbExclamation
        Exit Sub
    End If

    If swModel.GetType <> swDocASSEMBLY Then
        MsgBox "Active document is not an assembly!", vbExclamation
        Exit Sub
    End If

    Set swAssy = swModel

    ' Output file path (same folder as assembly)
    outputPath = Left(swModel.GetPathName, InStrRev(swModel.GetPathName, "\")) & _
                 Replace(swModel.GetTitle, ".SLDASM", "") & "_mates.txt"

    fileNum = FreeFile
    Open outputPath For Output As #fileNum

    ' Write header
    Print #fileNum, "SOLIDWORKS MATE EXTRACTION"
    Print #fileNum, "Assembly: " & swModel.GetTitle
    Print #fileNum, "Path: " & swModel.GetPathName
    Print #fileNum, "Date: " & Now()
    Print #fileNum, "========================================"
    Print #fileNum, ""

    ' Get components
    Print #fileNum, "COMPONENTS:"
    Print #fileNum, "----------------------------------------"

    Set swConfig = swModel.GetActiveConfiguration
    Set swRootComp = swConfig.GetRootComponent3(True)
    vComps = swRootComp.GetChildren

    If Not IsEmpty(vComps) Then
        For i = 0 To UBound(vComps)
            Set swComp = vComps(i)
            compName = swComp.Name2
            Print #fileNum, "  " & compName
        Next i
    End If

    Print #fileNum, ""
    Print #fileNum, "Total Components: " & (UBound(vComps) + 1)
    Print #fileNum, ""

    ' Get mates
    Print #fileNum, "MATES:"
    Print #fileNum, "----------------------------------------"

    Dim mateCount As Long
    mateCount = 0

    Set swFeat = swModel.FirstFeature
    Do While Not swFeat Is Nothing
        If swFeat.GetTypeName2 = "MateGroup" Then
            Set swSubFeat = swFeat.GetFirstSubFeature
            Do While Not swSubFeat Is Nothing
                If InStr(swSubFeat.GetTypeName2, "Mate") > 0 Then
                    Set swMate = swSubFeat.GetSpecificFeature2
                    If Not swMate Is Nothing Then
                        mateName = swMate.Name
                        mateType = GetMateTypeName(swMate.Type)

                        comp1 = ""
                        comp2 = ""

                        ' Get mated components
                        On Error Resume Next
                        Dim entCount As Long
                        entCount = swMate.GetMateEntityCount

                        If entCount >= 1 Then
                            Set swMateEnt = swMate.MateEntity(0)
                            If Not swMateEnt Is Nothing Then
                                Set swComp = swMateEnt.ReferenceComponent
                                If Not swComp Is Nothing Then
                                    comp1 = swComp.Name2
                                End If
                            End If
                        End If

                        If entCount >= 2 Then
                            Set swMateEnt = swMate.MateEntity(1)
                            If Not swMateEnt Is Nothing Then
                                Set swComp = swMateEnt.ReferenceComponent
                                If Not swComp Is Nothing Then
                                    comp2 = swComp.Name2
                                End If
                            End If
                        End If
                        On Error GoTo 0

                        Print #fileNum, "  " & mateName & " | " & mateType & " | " & comp1 & " <-> " & comp2
                        mateCount = mateCount + 1
                    End If
                End If
                Set swSubFeat = swSubFeat.GetNextSubFeature
            Loop
        End If
        Set swFeat = swFeat.GetNextFeature
    Loop

    Print #fileNum, ""
    Print #fileNum, "Total Mates: " & mateCount

    Close #fileNum

    MsgBox "Mate data exported to:" & vbCrLf & outputPath, vbInformation

End Sub

Function GetMateTypeName(mateType As Long) As String
    Select Case mateType
        Case 0: GetMateTypeName = "Coincident"
        Case 1: GetMateTypeName = "Concentric"
        Case 2: GetMateTypeName = "Perpendicular"
        Case 3: GetMateTypeName = "Parallel"
        Case 4: GetMateTypeName = "Tangent"
        Case 5: GetMateTypeName = "Distance"
        Case 6: GetMateTypeName = "Angle"
        Case 7: GetMateTypeName = "Unknown"
        Case 8: GetMateTypeName = "Symmetric"
        Case 9: GetMateTypeName = "CamFollower"
        Case 10: GetMateTypeName = "Gear"
        Case 11: GetMateTypeName = "Width"
        Case 12: GetMateTypeName = "Lock"
        Case 13: GetMateTypeName = "Screw"
        Case Else: GetMateTypeName = "Other(" & mateType & ")"
    End Select
End Function
